org.uqbar.project.wollok.tests/pom.xml
When `mvn tests` runs no US location and English language **org.uqbar.project.wollok.tests** fails. So set these arguments in **pom.xml**.
=> Set jvm params configuration for maven surefire plugin.

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/namedobjects/NamedObjectInheritanceTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/formatter/WollokFormatterTestCase.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokDsl.xtext, org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting/WollokDslFormatter.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/AbstractWollokCallable.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Not yet implemented for object literals. Not sure about the syntax.
This fixes #159  at least for named objects.
Also fixes #127
=> Adding support for named objects to inherit from a class

README.md
I propose this change because the current link refers to the xtext's last version.
Greetings!
=> Repair xtext 2.7.3 link

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/examples/TrenesTestCase.xtend
`TrenesTestCase` was called `MonstersIncTestCase`
=> Fixing class name

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/VisualComponent.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Window.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/ArrowListener.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/CollisionListener.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/GameboardListener.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/KeyboardListener.xtend, org.uqbar.project.wollok.lib/src/wollok.wlk, org.uqbar.project.wollok.lib/src/wollok/lib/WgameObject.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/CollisionListenerTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/PositionTest.xtend
- Collision Listeners are removed when remove its visual
- Positions can remove all visuals in itself
- wgame.stop() finish the game
- Any visual can talk (https://github.com/uqbar-project/wollok/issues/488) and large balloon messages are splitted in many shorters
=> Fix #588 removing collision listeners

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/model/WollokTestState.java
Temporarily disable linking to the URI of the error source, since it is not available.
Until that is fixed I provide a link to test header.
=> Fix #507 Double-clicking on a test raises a Java null pointer exception

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/mixins/MixinsTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/namedobjects/NamedObjectInheritanceTest.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokDslScopeProvider.xtend
For the moment, I only changed scope(WNamedObject namedObject) to consider the parent's scope as well. I didn't include mixins because I wasn't sure about what was expected on that aspect (not sure if NamedObjects will be expected to be mixed in in the future).
All preexistent test cases pass and the additioned objectInheritFromCustomClassWithInstanceVariable test case in NamedObjectInheritanceTest is also green after the fix.
In an unrelated topic, after I made the change I noticed that the following files were also updated and git prompted me to include them in the commit, but I think they just need to be ignored and not commited (they are listed in .gitignore files under org.uqbar.project.wollok.typeSystem.xsemantics\xsemantics-gen\org\uqbar\project\wollok\semantics): …
=> #603 Fix for variable scope of NamedObject

org.uqbar.project.wollok.launch/META-INF/MANIFEST.MF, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsolePage.xtend
Close #634 and #421 
The changes are:
- Create the HOME/END keys behavior.
- Launch the REPL and get focus immediately.
- Capture the left-click event and if cursor is at the last line and it's in the read-only zone, moves after the prompt.
=> Dev 1.4 #634 #421 repl issues

org.uqbar.project.wollok.game.ui/pom.xml, org.uqbar.project.wollok.game/pom.xml, org.uqbar.project.wollok.launch/pom.xml, org.uqbar.project.wollok.lib/pom.xml, org.uqbar.project.wollok.product.ui.feature/pom.xml, org.uqbar.project.wollok.product.ui/pom.xml, org.uqbar.project.wollok.product/pom.xml, org.uqbar.project.wollok.releng/pom.xml, org.uqbar.project.wollok.sdk/pom.xml, org.uqbar.project.wollok.targetplatform/pom.xml, org.uqbar.project.wollok.tests/pom.xml, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/classes/InstanceVariableInitializationTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/classes/MethodTest.xtend, org.uqbar.project.wollok.typeSystem.xsemantics.ui/pom.xml, org.uqbar.project.wollok.typeSystem.xsemantics/pom.xml, org.uqbar.project.wollok.typeSystem/pom.xml, org.uqbar.project.wollok.ui.diagrams/pom.xml, org.uqbar.project.wollok.ui.launch/pom.xml, org.uqbar.project.wollok.ui/pom.xml, org.uqbar.project.wollok.updatesite/pom.xml, org.uqbar.project.wollok/pom.xml, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend
Closes #645. Fix the problem like this:
```
object abc {
var x = 20
var y = x * 2
method getY() {
return y
}
}
```
But the solution have a precedence problem. If you code something like this:
```
object abc {
var y = x * 2
var x = 20
method getY() {
return y
}
}
```
It doesn't work because when evaluate the right side of the **y** declaration wasn't evaluated.
=> Change the right side evaluation at declarations

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ExceptionTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ConstructorShouldNotCallSuperInBody.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
The idea is to fix this issue #644 
This fix adds the report of the error of using super in a constructor. 
The correct syntax for delegating in the constructor is:
``` constructor(mensaje, algo) = super(mensaje) {
value = algo
}```
=> Adding report of the error when super is used in the constructor

org.uqbar.project.wollok.lib/src/wollok.wlk, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
I have fixed when showing duplicated numbers in a List. It is the same behavior when an object has two instances variables with the same numeric value.
=> Dev 1.4 #641 printing duplicated elements in list

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/AbstractWollokInterpreterTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/RangeTestCase.xtend
Making a mini pull request just to notify everyone there is now a test method that simplifies testing.
Instead of doing
``` java
@Test
def void filterStepMinus3() {
'''
program a {
const range = 8 .. 1
range.step(-3)
assert.equals([8,2], range.filter({ elem => elem.even() }))
}
'''.interpretPropagatingErrors	
}
```
You can do:
``` java
@Test
def void filterStepMinus3() {
'''
const range = 8 .. 1
range.step(-3)
assert.equals([8,2], range.filter({ elem => elem.even() }))
'''.test	
}
```
=> New feature "test" method - issue #737

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ObjectTest.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/linking/WollokLinker.xtend
Close #765 
The problem was anonymous objects didn't inherits from Object, so I added WObjectLiteral in the _WollokLinker_.
Then Wollok fails on execute `toString()` method, and it was because the Interpreter didn't add the inherits elements (and its natives). I change the `evaluate(WObjectLiteral l)` method in _WollokInterpreterEvaluator_ and delegate some duplicated code into methods.
1. On add `getParentRef(WObjectLiteral wObject)` in the multi-method I get a compilation error: `Type mismatch: cannot convert from EObject to WMethodContainer`. 
I'm not sure why, but I can fix it adding a definition for EObject: `getParentRef(EObject wObject)`. 
But It's sounds to _hack_, there is other solution?
2. Wollok has a bug on printing objects with a Double property type: …
=> Dev #765 anonymous objects are not printable

org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/ClassDiagramView.xtend
This fixes the horrible bug #680
Seems like if you put a document listener into an xtext document and you perform a task that takes some time (like layout the class diagram) screws other parts of the editor.
What I've done is, probably what should have been done always, to run the listener code in a separated UIJob scheduled to be run in another moment.
So that it won't interfere with the editor behavior.
It now works fine.
My only explanation for other cases when people saw this happening in xtext own editor (and not just in wollok) is that they also have some listener that, sometimes takes longer and screws it up).
Fixes #680
=> Fixes #680  glitch in editor corrupts the view

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/perspectives/WollokCodingPerspectiveFactory.xtend
Just static diagram in Wollok Perspective is hidden. Nothing else.
=> Issue #681 - Static diagram temporarily hidden for Wollok perspective

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsolePage.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/editor/WollokReplStyledText.xtend
Tried with one and many lines. Now you can paste text previously copied in REPL console.
It's not platform dependant, fortunately.
=> Fixing issue #819 - pasting text in a REPL console

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/VisualComponent.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/debugger/server/XDebuggerImpl.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/debugger/server/XDebuggerState.xtend, org.uqbar.project.wollok.lib/src/wollok/lib.wlk, org.uqbar.project.wollok.lib/src/wollok/lib/ConsoleObject.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/AbstractWollokInterpreterTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ListTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend, org.uqbar.project.wollok.typeSystem.xsemantics/src/org/uqbar/project/wollok/typesystem/substitutions/CheckTypeRule.xtend, org.uqbar.project.wollok.typeSystem.xsemantics/src/org/uqbar/project/wollok/typesystem/substitutions/FactTypeRule.xtend, org.uqbar.project.wollok.typeSystem.xsemantics/src/org/uqbar/project/wollok/typesystem/substitutions/SubstitutionBasedTypeSystem.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokCodeHighLightLineStyleListener.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/refactoring/ExtractMethodHandler.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/QuickFixUtils.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/WollokProjectFactory.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/objects/NewWollokObjectsWizard.java, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/program/NewWollokProgramWizard.java, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/tests/NewWollokTestWizard.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/XTextExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/XtendExtensions.xtend, org.uqbar.project.xinterpreter/src/org/uqbar/project/xtext/utils/XTextExtensions.xtend
- Creates method ```newline``` in the console WKO and its corresponding native class to be able to get the OS implementation: ```\n``` for Unix-like systems and ```\r\n``` for Windows.
- Replaces hardcoded ```\n```s in the code with either System.lineSeparator (XTend code) or console.newline() (Wollok code).
=> Dev #828 line separator

org.uqbar.project.wollok.releng/pom.xml
Close #882
I found [this tutorial](https://eclipse.org/Xtext/documentation/350_continuous_integration.html) to work with xtext + maven. When i go to code it, i found that is already coded. I fix the releng pom file that contains the misplaced plugin configuration. 
The additional configuration form maven-clean-plugin at org.uqbar.project.wollok project it's ok because the scm-gen files need to be cleaned in this project. [Here is](https://kthoms.wordpress.com/2011/10/06/xtext-maven-and-source-control/) an explanation.
=> Fix maven-clean-plugin for xtend-gen directories

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
Change in Number.times() implementation in order to make it a void method instead of returning null.
=> Fix #864 - Change Number.times() to void instead of null

org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend
Numbers should always understand these messages, and so they're added as abstract methods in Number.
Implementation for both messages on Integer class is added.
=> Add roundUp(n) and truncate(n) to Integer

org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/AbstractWollokQuickFixTestCase.xtend
After removing the conflicting dependency Eclipse complaints that we are using a target platform which is newer than my eclipse instalation. I do not how to fix that. Everything seems to work, though.
=> Possible fix for #1006. Remove conflicting location for target platform.

org.uqbar.project.wollok.lib/src/wollok/lang/Range.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/RangeTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/AbstractWollokQuickFixTestCase.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/XtendExtensions.xtend
The native implementation was wrong calculating the range size.
At first, I thought that changing it for:
```
((Math.random * wrapped.size) + wrapped.start).intValue()
```
should be good. But it **fails** when step != 1.
So I create a _XtendExtension_ for lists that returns an element al random (with equal probability).
Close  #1003
=> Fix random in range

org.uqbar.project.wollok.lib/src/wollok/lang/WDouble.xtend, org.uqbar.project.wollok.lib/src/wollok/lang/WInteger.xtend, org.uqbar.project.wollok.lib/src/wollok/lang/WNumber.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend
I changed Wollok default to 5 decimals for division. If you want you can use a constant.
Unified division algorithm in WNumber (see div(BigDecimal, BigDecimal) method).
=> Common division algorithm for integers and decimals #1016

org.uqbar.project.wollok.lib/src/wollok/lang/WDouble.xtend, org.uqbar.project.wollok.lib/src/wollok/lang/WNumber.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
Original issue #904 
- Using a common definition in WNumber for decimal operations: add. subtract, multiply, divide, remainder
- Created several test cases for decimal numbers.
=> Fix #904 - Decimal numbers operations

org.uqbar.project.wollok.product/plugin_customization.ini
By default it will show line numbers in editor.
To test it, you have to do a mvn clean install and open targeted product.
=> Adding line numbers in editor (default) #586

org.uqbar.project.wollok.ui.launch/plugin.xml, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/handlers/LaunchReplWithoutFileHandler.xtend, org.uqbar.project.wollok.ui/META-INF/MANIFEST.MF, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/view/WollokViewerFilter.java
It fixes the issue #739.
I have created a workaround for this.
Basically I am creating (or reusing) an empty project, this project is hidden in the view.
I have chosen this approach because to run as a external tool, the whole classpath for the bundle should be calculated (it need the launcher, the lib, and all the xtext / eclipse dependencies). This is calculated in the build to generate the scripts to run from the console but they are not persisted. Even accesing to this classpath, it should be transformed to get the JARs from the plugins directory.
Maybe a better implementation can recalculate this classpath and store them for usage.
Please @fdodino, check if this is good enough.
=> Running the REPL alone - Adding a workaround creating a hidden project

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/GetterShouldReturnValueQuickFixTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/QuickFixTest.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/Messages.java, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Fixes #310 
Adding some quickfixes to solve the getter should return value. 
Reuse of the existent "Prepend return" and I18N of it.
=> Adding quickfixes for 'getter should return value'

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ClassInherintingFromCyclicHierarchy.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ClassInherintingFromCyclicHierarchy.wlk2.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ClassInherintingFromCyclicHierarchyMultipleClasses.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ClassInherintingFromSameClass.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Well, it fixes not only
``` scala
class B inherits B { }
```
but also
``` scala
class A inherits B { }
class B inherits A { }
```
Added Xpect tests also. And fixes stack overflow problem in validations.
=> Fix #279 cyclic hierarchy

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/abstractWizards/AbstractNewWollokFileWizardPage.java
During Hackaton, trying to use New Objects and Wollok Wizard I discovered a bug in Windows installation.
The wizard verifies if a certain file already exists, so I used URLEncode to fix it.
=> Fixing Validation of  New Objects and Classes Wizard for Windows

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CheckMethodReturnOverriding.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
I find in WollokModelExtensions this: 
`def static dispatch boolean returnsOnAllPossibleFlows(WThrow it) { true }`
Throw not always must be modeled to return a **true** value on it's flow. It depends if the super method have a return value or not. So WThrow need to have the same behavior.
=> Dev #1045 incorrect error marked regarding returns in overriden method

org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
I've defined a constant **_wollokDslValidator_TESTS_IN_FILE_** with the content of the error message.
Also I noticed that a "CLASSES_IN_FILE check" is missing.
Should I fix it in this PR or create a new issue?
=> fix-#1089 wrong error message when a test is defined in a .wlk file

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokDsl.xtext
In order to fix the precedence bug I added a new rule to the grammar:
```
WExponentiativeExpression returns WExpression:
WUnaryOperation (=>({WBinaryOperation.leftOperand=current} feature=OpPower) rightOperand=WExponentiativeExpression)?;
OpPower:
'**';
```
Now `a * b ** c` equals `a * (b**c)` as expected.
=> fix #1052 exponentiation precedence 

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchShortcut.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/shortcut/WollokAllTestsLaunchShortcut.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/shortcut/WollokTestLaunchShortcut.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WEclipseUtils.xtend
Now you have a Confirm Dialog message.
It works for Tests and Programs, it does also work for REPL console when not using .wlk with errors.
Also i18n messages were added.
=> Fix #394 - Add a Confirm Dialog

org.uqbar.project.wollok.product.ui/plugin.xml, org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/startup/OpenDebugPerspectiveOnStartup.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/perspectives/WollokCodingPerspectiveFactory.xtend
Adding the opening of the debug perspective in the startup to allow it appear in the switch perspective
Fixes #468
=> Debug Perspective in Switch Perspective

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
Well, it is not a real fix on #1110, but it fixes indentation of new methods created by Quick Fix Provider.
=> Fixing indentation for method creation

org.uqbar.project.wollok.typeSystem.xsemantics.ui/src/org/uqbar/project/wollok/typeSystem/xsemantics/ui/preferences/TypeSystemConfigurationBlock.xtend
I let it here, I will not push the Red (green) button. 
It only applies to new workspaces, old workspaces with the setting in TRUE are not changed.
=> Disabling TS :(

org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokConstants.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokDslScopeProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokImportScope.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokImportedNamespaceAwareLocalScopeProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokQualifiedNameProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/serializer/WollokDslSyntacticSequencerWithSyntheticLinking.xtend
I have reimplemented a custom Importing Scope schema. 
Having so permited us to know completely what are the rules to look up of the elements and it is simpler than the one implemented in Xtext, as the one implemented in xtext is more general and permits use cases that we don't need.
=> Improving performance in imports

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/interpreter/WollokREPLInterpreter.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherInterpreterEvaluator.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokExceptionUtils.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/errorHandling/StackTraceElementDTO.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/errorHandling/WollokExceptionExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreter.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokNativeLobby.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/AbstractWollokDeclarativeNativeObject.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend, org.uqbar.project.wollok/src/wollok/lang/Exception.xtend, org.uqbar.project.xinterpreter/src/org/uqbar/project/wollok/interpreter/context/CompositeEvaluationContext.xtend, org.uqbar.project.xinterpreter/src/org/uqbar/project/wollok/interpreter/context/EvaluationContext.xtend, org.uqbar.project.xinterpreter/src/org/uqbar/project/wollok/interpreter/context/MapBasedEvaluationContext.xtend
Today if you have this test:
```javascript
class Ave {
method volar() {
const x = 1 / 0
}
}
test "testX" {
assert.that(true)
}
test "use empty"{
new Ave().volar()
assert.equals(true)
}
```
- Stacktrace is reversed
- If you have isolated tests everything works fine, but if you have a describe, then its file definition is printed in stack trace (see the line test.wtest:1, which points to file definition):
- A program like this
```javascript
import example.*
program abc {
console.println('Hello Wollok')
new Ave().volar()
}
```
produces this output:
```bash
Hello Wollok
wollok.lang.Exception: / by zero
at wollok.lang.Integer./(other) [/lang.wlk:1094]
at example.Ave.volar() [/example.wlk:5]
at  [/program.wpgm:6]
```
So stack trace is also reversed, but also links to source files does not work, …
=> Stack trace fixes

org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target
Replaces current plugin version (4.9) with required plugin 4.8 for Wollok 1.6
=> Replacing current to archived repository for egit

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokDslUiModule.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/validator/WollokResourceUIValidatorExtension.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
When saving a file the problems markers are processed for that file and the files related to the saved one.
Fixes #1294
=> Saving a file triggers the analysis of related files.

org.uqbar.project.wollok.typeSystem.xsemantics.ui/src/org/uqbar/project/wollok/typeSystem/xsemantics/ui/labeling/XSemanticsWollokTypeSystemLabelExtension.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/AbstractContainerWollokType.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokTypeSystemActivator.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/AbstractInferenceStrategy.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/MaxTypesFromMessages.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MaximalConcreteTypes.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/SimpleTypeInfo.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeInfo.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/labeling/WollokDslLabelProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/NotConfigurable.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
This configuration changes makes type system run when a file is saved instead of running while the user types. After testing it in a few projects, performance seems reasonable.
=> Avoid to run type system while typing

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/Image.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/ImageSize.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Background.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Cell.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Window.xtend, org.uqbar.project.wollok.lib/src/org/uqbar/project/wollok/lib/WImage.xtend, org.uqbar.project.wollok.lib/src/wollok/lib.wlk, org.uqbar.project.wollok.lib/src/wollok/lib/GameObject.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/BackgroundTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/GameboardTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/ImageTest.xtend
Fixes #1192
- `game.ground("image.png")` -> sets **cells** image
- `game.boardGround("image.png")` -> sets **full game** image
- Cells and game images adapt its size respectively
- For other components, the original image size is kept
=> Game general background

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/constructors.wlk.xt, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstructorConstraintsGenerator.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/editor/annotations/WOverrideIndicatorModelListener.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
I understand that this covers all "traditional" constructors, both in the directly reference class and inherited. I used the look up strategy already present (`resolveConstructor`). @fdodino please verify my logic.
We should create another issue / pr for automatic (name-based) initialization which is not considered anywhere in TS.
=> Fix 1346 constructor call constraints

org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
Actually, if you run tests in the dev env, it produces no warnings, but the prod env does. If searched for the two reported message strings and they do not seem to be used, so I propose to remove them.
=> fix: remove unused messages

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend
Just a simple empty catch to avoid an error log
=> Fix #1443 - Outline page refresh without ClassCast

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokAnsiColorLineStyleListener.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokConsoleColorPalette.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokReplConsolePageParticipant.xtend
Fixes #1324 . Now , console in Mac shows responses only in Black (no link underlined, no error in red, no values in blue). Normal behavior tested in Linux.
In a (near) future, we should upgrade Eclipse to Oxygen, and use SWT's latest solved version...
=> Fix #1324 repl console mac

org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/RecursiveToStringTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/SetTestCase.xtend
Estamos resolviendo los issues #1401 y #1414 , poniendo en la balanza que es preferible evitar un stack overflow en lugar de mostrar en forma elegante los elementos de una colección (por eso #1305 quedará en wontfix).
=> Fix #1401 - recursive relationships lead to stack overflow in toString

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/list.wlk.xt, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/GenericType.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/CollectionTypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeAnnotation.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/AnnotatedTypeRegistry.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/MethodTypeSchema.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClassParameterTypeVariable.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/CompoundSelfTypeVariableSchema.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/CompoundTypeVariableSchema.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ITypeVariable.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableOwner.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableSchema.xtend
Now #[].filter(...) returns a list and #{}.filter(...) returns a set.
Even if both are the same method filter from collection.
Also, several list methods have been typed, see list.wlk.xt for details.
=> Fix #1479 self type return

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
El editor trabaja con un mapa de issues cacheados que se refresca cada vez que se corre el builder con o sin el Type System. El problema que ocurría era que el mapa utiliza como clave el resource, que funcionaba ok si trabajabas dentro del workspace pero no si lo importabas desde otro directorio (workspaceURI no te servía, y cuando quería parsear el archivo quedaba un path inconsistente, grababa platform y chequeaba contra un file con path absoluto, nunca matcheaba y quedaba la marca gris porque no lo reconocía).
De paso eliminamos del chequeo de issues aquellos resources que generan del import, y que dan error.
=> Fixing #1477

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Messages.java, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherInterpreterEvaluator.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages.properties, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages_es.properties, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokExceptionUtils.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokRemoteTestReporter.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/json/WollokJSONTestsReporter.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/TestTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/WollokComparisonFailure.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/natives/NativeTestCase.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/errorHandling/WollokExceptionExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterConsole.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/natives/DefaultNativeObjectFactory.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
Acá hice dos cosas, por un lado mejoré el mensaje de error cuando el class loader quiere cargar una clase y no existe (también agregué un test), y por otra parte el stack trace de Java en la consola es algo que causa muy mala impresión, la anulé por el momento. La mayoría de las veces resolvemos esas cuestiones replicando el incidente por lo que el stack trace de java con código xtend es poco útil.
=> Fix #1404 - fake native class throws an ugly exception

org.uqbar.project.wollok.lib/src/wollok/lib.wlk, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ExceptionTestCase.xtend
Instead of a red bar, now there is an orange one for expected exceptions not thrown.
=> Fix #1504 assertion exception for expected exception

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/ConstructorsQuickFixTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/NamedObjectVariableInitialization.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/NamedParameters.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/UnusedVariable.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Bueno, en el issue #1519 está la definición de lo que hice, básicamente evitar la validación de variables y constantes sin inicializar si la clase no tiene constructores (en los wko quedó igual, agregué tests). Si tenemos constructores, se validan en cada uno que el objeto quede bien construido (que no haya variables o constantes sin inicializar).
=> Fix #1519 non initialized variables and const in method containers

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/literals.wpgm.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/nullLiterals.wpgm.xt, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
Fixes https://github.com/uqbar-project/wollok/issues/1508
This PR only create a generic type variable for each NullLiteral.
=> Ts null literal

org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/labeling/WollokTypeSystemLabelExtensionImpl.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/MessageType.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/UnionType.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokType.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/contentassist/WollokDslProposalProvider.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/labeling/WollokTypeSystemLabelExtension.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/ResourceUtils.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/AbstractConfigurableDslValidator.xtend
Today, you must save the file in order to get all updated autocomplete options.
It also supports union types:
(it repeats methods from each polymorphic definition, because they may have different wollok docs)
Implementation of StringType and IntType (both from Type System) lacks a proper allMessages() methods, returning an empty arraylist. This causes no effect on autocomplete, because String and NumberLiteral use a different algorithm. But I think we could enhance them for future uses.
=> Autocomplete with typesystem

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/ReturnInParameterQuickFixTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/cannotReturnAssignment.wlk.xt, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/Messages.java, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Added new validation and changed validator for "return" in method to avoid a misleading "Must return on every possible flow" message.
Added also a quick fix in order to remove "return" keyword.
I'd like to review the error reported and quick fix messages too.
=> Fix #1491 - validation and quick fix for return expression in parameter

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/PropertiesDefinition.wtest.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
Wollok doesn't let abstract methods to be implemented by properties.
For example, with this code:
```
class Arma {
method artefacto()
}
class EspadaVisual inherits Arma {
const property artefacto = new Espada()
}
```
doing a `new EspadaVisual()` raises an error, because it doesn't implement the abstract method `artefacto`.
Change the logic we use in the validator to take properties into account when determining the non-implemented abstract methods.
=> #1564 Fix property validation to let them implement abstract methods

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/GlobalConstantsTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/parser/FixtureParserTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/GlobalConstants.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/parserErrors/MisplacedInstanceVariable.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokDsl.xtext, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokNativeLobby.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/parser/WollokSyntaxErrorMessageProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokResourceDescriptionStrategy.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/rules/DontCompareEqualityOfWKORule.xtend
Se permiten las constantes a top level (junto con clases y named objects).
Se agregan validaciones de no duplicación de nombres y no colisión con named objects.
Se valida también que sólo se declaren constantes, las variables siguen prohibidas.
=> Fix #1231 constantes globales

org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/builder/WollokTypeSystemBuilderParticipant.xtend
El error sólo se produce si el type system está desactivado, está refrescando el outline y los errores siempre, esté activado o no. Muevo los refrescos dentro del if.
Como consecuencia, si deshabilitamos el type system y no le damos rebuild, los errores de tipos preexistentes quedan para siempre. Se podría mejorar pero creo que es aceptable; un clean limpiaría los errores.
=> Fix #1611.

org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/builder/WollokTypeSystemBuilderParticipant.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend
Fix #1616
We should generate errors and refresh views **always** in _BuilderParticipant_
=> Refresh problems view

org.uqbar.project.wollok.lib/src/wollok/lib.wlk, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/asserts/AssertTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/natives/ExceptionPropagationInNativeTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/SetTest.xtend
Funny thing is that we had an error in our sanity tests (using `assert.equals` instead of `assert.that`).
=> Fixing assert.equals() when used with one parameter

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Messages.java, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokFormatter.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherParameters.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages.properties, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting2/WollokDslFormatter.xtend
This will allow `wollok-cli` to run formatter externally:
You can do
```bash
wollok format pepita.wlk // prints formatted file directly to the console
wollok format pepita.wlk -save // saves formatted file directly into pepita.wlk
```
=> Formatter cli #1666

org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.lib/src/wollok/lang/WDate.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/DateTestCase.xtend
It looks like I forgot to create this PR during last hackaton.
now `someDateObject.dayOfWeek()` returns an object representation for days of the week instead of an integer. Note that now exists `internalDayOfWeek()` which returns an integer.
=> fix: #1241 - dayOfWeek() returns object

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/Messages.java, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/VisualComponent.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Window.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/TimeListener.xtend, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/messages.properties, org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/messages_es.properties
Dos arreglos:
- #1663 Game se cuelga al lanzar error con más de un salto de línea
- #1669 game.sound() tira un error cuando el juego no arrancó (no es la solución, evitamos un error feo y lo reemplazamos por una sugerencia ya que el diseño del juego requiere pensar bien una alternativa)
A futuro quedan otros issues que necesitan más definición
=> Wollok game issues

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/failureMessages.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/inheritParameters.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/super.wlk.xt, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
Fix #1600
Fix #1569
Fix #1615
Estos problemas era causados por la unificación entre argumentos y parámetros. Creo que esas relaciones deberían estar aparte de las generales de sub/super tipo, ya que debe postergarse hacia el final del proceso de inferencia, por si se detectan errores.
=> Fix some ts errors

org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/preferences/TypeSystemConfigurationBlock.xtend, org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/preferences/WollokTypeSystemUIPreferences.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/preferences/DefaultWollokTypeSystemPreferences.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/preferences/WollokCachedTypeSystemPreferences.xtend
Fix #1468
Después de 6 horas de pruebas...
=> TS enabled by default

org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/CollectionTest.xtend
- Se agregan las funcionalidades `copyWith` y `copyWithout` en las que se habla en [#1518](https://github.com/uqbar-project/wollok/issues/1518)
`copyWith` retorna una nueva lista con el elemento que le pases por parametro al final
`copyWithout` retorna una nueva lista sin el elemento especificado por parametro
=> Feature : copy and copywithout

org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.lib/src/wollok/lang/WDate.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/base/AbstractWollokParameterizedInterpreterTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/AbstractWollokInterpreterTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/DateTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/PairTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/StringTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/WollokXPectTest.xtend
La idea de este PR es hacer que el toString del Date de Wollok en lugar de imprimir
`>> a Date[day = 23, month = 1, year = 2019]`
imprima
`>> 23/1/19`
En sí el cambio está terminado. El problema que estoy teniendo viene por decisiones que tomamos al definir el formato para el toString. Decidimos hacer que el toString respete el locale del usuario, es decir, que lo formatee según la región del usuario. Esta decisión respeta mejor los formatos estándar pero requiere ciertas consideraciones al correr los tests, por ejemplo, que dependiendo de la máquina que corra los tests (en particular del locale de la maquina) los tests van a pasar o no.
Bueno, para evitar que esto pase es que intenté cambiar el formateador que usa el WDate (el objeto java que se encarga de hacer este toString por detrás) …
=> Feature #1692 change to string of date

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/wollokDoc/WollokDocParser.xtend
Una mejora que se me ocurrió en los métodos de wollokdoc, es agregarle el tag code, para que los paréntesis y los parámetros no queden tan separados. Lo mismo para los métodos heredados.
=> Using code tag instead of plain html

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/MethodTypeInferenceTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/asserts.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/console.wpgm.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/void.wpgm.xt, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/CollectionTypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/NumberTypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokGameTypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokLibTypeDeclarations.xtend, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
=> Bye Any type in declarations

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CheckOnNameStyles.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
=> fix #1739 - Definición de una constante por fuera de un container me pide que inicie en minúscula

org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.lib/src/wollok/lang/WCollection.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
Mi idea fue ponerle native a asSet y usar el toSet de IterableExtensions que respeta el orden.
=> Fix #1743 - without duplicates de list no respeta el orden

org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokGlobalScopeProvider.xtend
Una posible solución al problema del Update dirty state editor. Eliminé varios synchronized que colgaban del método principal `objectsFromLocalImport`, que es el que ahora vuelve a tener un synchronized.
Probé renombrar un archivo y no se colgó, intenté forzar un error y grabar al toque para ver si aparecía el problema de concurrencia y no se dio. Me gustaría ver cómo se comporta en otras máquinas antes de liberarlo (ej: pull a dev y cuando intentemos levantar el Runtime de dev no debería ocurrir un deadlock)
=> Test: fixing dirty state editor

org.uqbar.project.wollok.typeSystem/META-INF/MANIFEST.MF
Bueno, el sábado arreglé esto en un branch, pero como estamos esperando para mergearlo por otra cosa, todavía no está en dev. En otro PR también lo arreglé, pero me resulta molesto que cada vez que arranco del branch dev me salta el error de dependencias del type system.
@PalumboN lo voy a mergear directamente para no tener más problemas.
Atte.
La Gerencia
=> Fix dependency in type system MANIFEST

org.uqbar.project.wollok.lib/src/wollok/game.wlk, org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend, org.uqbar.project.wollok.typeSystem/META-INF/MANIFEST.MF, org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/CollectionTypeDeclarations.xtend
Fixes #1779 
Also fixes `tsVarOrParam` method for type system @PalumboN
=> Fix #1779 - replace unique method name

org.uqbar.project.wollok.lib/src/wollok/lang.wlk, org.uqbar.project.wollok.lib/src/wollok/lang/WCollection.xtend, org.uqbar.project.wollok.lib/src/wollok/lang/WList.xtend, org.uqbar.project.wollok.lib/src/wollok/lang/WSet.xtend, org.uqbar.project.wollok.lib/src/wollok/lang/WollokObjectComparator.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/SetTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ListTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/SetTest.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/api/WollokInterpreterAccess.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
- `asSet()` deja de ser native y `withoutDuplicates()` ya no lo usa. 
- Agrego tests para `asSet()` y `withoutDuplicates()`
Después de arreglar las inconsistencias relativas al issue, note este caso que seguía pasando:
Cuando el set era de distintos tipos, cada tanto se "comía" un duplicado (siempre eran Strings y Dates).
Lo pude solucionar con un cambio en el método `compare()` de `WollokObjectComparator`. Hay que revisarlo.
Fixes #1771 and #1783
=> Fix #1771 - inconsistencias en list.asSet()

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/DefaultWollokTestsReporter.xtend, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokConsoleTestsReporter.xtend
@npasserini is this a better approach? Now you see all errors in the final report:
This PR also fixes a problem when an exception is thrown in fixture or test/describe initialization.
You can check this changes, I'd like to ship it for next release (Oct 20th maybe?)
=> Fix #1841 test runner

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/namedobjects/NamedObjectTestCase.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CheckVarReferences.wpgm.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ConstructorAndConsts.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/NamedParameters.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/parserErrors/MisplacedInstanceVariable.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/errorHandling/HumanReadableUtils.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/linking/WollokLinkingDiagnosticMessageProvider.xtend
Bueno, algo que me molestaba desde hace tiempo es que diga "Referenciable" en los mensajes de error cuando el linker no encuentra una referencia. Creo que lo mejor es simplemente remover esa palabra, con el contexto del código y el mensaje actual creo que es suficiente.
=> Fix referenciable linking error

org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target
Bueno, la gente de Babel liberó el 15/07/2020 la versión 0.18.0 y movió el repositorio p2 a archived. Este PR arregla el build que funciona todavía en Travis pero no en AppVeyor.
=> Fix Babel Repository moved to archived one

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/cannotReturnAssignment.wlk.xt, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Eso, le incorporé la validación reemplazando el `instanceof` por una solución polimórfica. De paso agregué tests, y sirve para cualquier operación binaria con asignación (ya estaba determinado esto por una expresión regular).
=> Fix #1894 Cannot return assignment with +=

org.uqbar.project.wollok.launch/Generate WollokDoc.launch, org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/wollokDoc/WollokDocParser.xtend
Como segundo paso, hay que agregar el wollokdoc a los pocos atributos que tenemos en wollok-language...
En un rato deberíamos poder verlo en producción: www.wollok.org/
=> Fix #1817 - adding attributes to wollokdoc

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/actions/WollokReplConsoleActionsParticipant.xtend, org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/messages_es.properties
=> Fix #1928 REPL Console when stopped should not warn about being outdated

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/MethodReturningBlockQuickFixTest.xtend, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/EffectlessExpressionsInSequence.wlk.xt, org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/MethodsReturningBlock.wlk.xt, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/Messages.java, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/QuickFixUtils.xtend, org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties, org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Bueno @PalumboN , mientras esperamos cambios en el lenguaje, me dio cosita no arreglar esto:
1) Se agregó la validación de los métodos que tienen definición con `=` y una expresión y validamos que la expresión no sea un bloque que no tenga parámetros.
2) De paso agregué un quick fix para que elimine el `=`
=> Fix #1938 - tirar un warning para métodos que tienen sintaxis rara

org.uqbar.project.wollok.lib/src/wollok/lib/AssertionException.xtend, org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/WollokJavaConversions.xtend
Resuelve el problema de cómo se muestra en Wollok los resultados cuando hay un assertion exception.
En la consola se sigue viendo con `<` y `>`:
y la idea es conservar el cambio así para no afectar wollok-language. Después ver cómo afecta eso a wollok-ts.
=> Fix assertion exception in wollok test result
