uqbar-project/wollok

.travis.yml
org.uqbar.project.wollok.launch/build.properties
org.uqbar.project.wollok.launch/wdk/bin/wrepl.sh
org.uqbar.project.wollok.lib/build.properties
org.uqbar.project.wollok.product/build.properties
org.uqbar.project.wollok.tests/pom.xml
org.uqbar.project.wollok.typeSystem.xsemantics.ui/build.properties
org.uqbar.project.wollok.typeSystem.xsemantics/build.properties
org.uqbar.project.wollok.updatesite/pom.xml
org.uqbar.project.wollok/build.properties

It does include:
- Adding the repl command for the command line.
- Improving the stability of the maven build, using JDK7 and version for all the plugins
- Fixing missing folders in manifests and build.properties.
Fixes #73 
Fixes #81 
Fixes #82 
Fixes #83

Various Hotfixes

---

.travis.yml
README.md
org.uqbar.project.wollok.releng/pom.xml

Using JaCoCo + Coveralls + maven plugin
Travis triggers the coverage
This is the site
https://coveralls.io/r/uqbar-project/wollok

Dev #72 code coverage

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/AbstractWollokDeclarativeNativeObject.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/collections/AbstractWollokCollection.xtend

 Fixing collection's equals and any() for single element collection

---

README.md

Listing tycho & buildhelper as required plugins, and listing how to install Xtext 2.7.3 from archive

Updating environment setup instructions in README

---

org.uqbar.project.wollok.ui.launch/plugin.properties
org.uqbar.project.wollok.ui.launch/plugin.xml
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/WollokTestResultView.xtend

Also refactoring tests view and updating run/debug label to remove "Launch" (redundant)

Fixes #223 adding Bar to tests view

---

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend
org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/WollokGDXApplication.xtend

Create a new LwjglApplication class. The main thread join to LwjglApplication thread and waits until it ends.
Close #543

the main thread join the mainLoopThread until it ends

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ExceptionTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/classes/MethodTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/clazz/ConstructorTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/namedobjects/NamedObjectInheritanceTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CannotModifyValues.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CheckOnNameStyles.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CheckVarAssignment.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ConstructorCalls.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ConstructorDelegation.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/NamedObjectInheritance.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ReturnInConstructors.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/TryCatch.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/UnusedVariable.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ValuesAsInstVarsAssignedInConstructor.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/VoidMethodsUsage.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/formatter/WollokFormatterTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokDsl.xtext
org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting/WollokDslFormatter.xtend
wollok-tests/src/wollok/classes/constructors/constructorsLib.wlk
wollok-tests/src/wollok/examples/guia2/clases_ej3_camiones.wlk
wollok-tests/src/wollok/examples/guia3/ej1_piratas.wlk
wollok-tests/src/wollok/examples/monstersinc/actividades.wlk
wollok-tests/src/wollok/examples/monstersinc/asistentes.wlk
wollok-tests/src/wollok/examples/monstersinc/asustables.wlk
wollok-tests/src/wollok/examples/monstersinc/asustadores.wlk
wollok-tests/src/wollok/examples/monstersinc/modelo.wlk
wollok-tests/src/wollok/examples/trenes/trenes.wlk
wollok-tests/src/wollok/exceptions/exceptionsLib.wlk
wollok-tests/src/wollok/typesystem/asusta.wlk

Introducing constructor token

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WSet.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ObjectTest.xtend

Issue #409 preludes collection messages

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/Imports.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/libForImports.wlk
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/editor/hyperlinking/UnresolvableCrossReference.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/editor/hyperlinking/WollokEObjectAtOffsetHelper.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokQualifiedNameProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokResourceDescriptionStrategy.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
wollok-tests/src/org/uqbar/wollok/packages/importingFromOtherFile.wlk
wollok-tests/src/org/uqbar/wollok/packages/otherFile.wlk

Dev #206 navigate imports

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WCollection.xtend
org.uqbar.project.wollok.lib/src/wollok/lib/AssertObject.xtend
org.uqbar.project.wollok.lib/src/wollok/lib/AssertionException.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/TestTestCase.xtend

Adding findOrElse and findOrDefault

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend

Adding times

---

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend
org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.lib/src/wollok/lib/WgameObject.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ImageTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/PositionTest.xtend

For add a visual object we can do
```Xtend
wgame.addVisual(visual)
```
or
```Xtend
position.drawElement(visual)
```
And for remove them
```Xtend
wgame.removeVisual(visual)
```
or
```Xtend
position.deleteElement(visual)
```

Dev #489 remove visual from board

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/program/NewWollokProgramWizard.java

Change "this.println" to "console.println"

---

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend

Close #594 
Just swap the height and width iterations when the tile image is created.

Swap height and width iterations.

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WList.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ListTest.xtend

Feature #510: Should be a way to have an ordered list
Adding sortBy to List (side-effect version) and sortedBy to Collection (no side-effect version: returns a new List).
Please let me know everything you see that can be improved.

Adding sorting methods to collections

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsolePage.xtend

Close #598 and #599 
The problem was the way that calculate de length of the text because ANSI escape codes inserts additional characters. So, the main change was call a StyledText getCharCount method. That solve the error.
:+1:

change the way that calculates the text length to position the cursor

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend

postfix op for increment gives error in the stack trace

Fixes #530

---

org.uqbar.project.wollok.lib/src/wollok/lang/WDouble.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WInteger.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/numbers/MixedNumberTypesOperationsTest.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/WollokJavaConversions.xtend

Ok, 
Basically WDouble is now BigDecimal. That solves the problem of multiplication, etc but... (_allways have a but_)..... BigDecimal have no fractional pow(). The only way i found to fix this without an external library is to use Math.pow(a,b) and convert BigDecimal to double :-1:

change Double to BigDecimal

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/debugger/WollokDebugModelPresentation.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/WollokTestResultView.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/model/WollokTestState.java

Fixed all ViewPart and LabelProvider that use images and colors
Close #647

Fix testing and WollokDebugModelPresentation icons and colors

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend

Fix the quick fix :P required superclass constructor

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties

Removing unused messages

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/OverrideMethodsFromObject.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/Overrides.wlk.xt
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/editor/templates/WollokTemplateProposalProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties

fix closure template, constructor template and text overrideS

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend

Implements methods requested on #691.

Add methods sum(), min() and max() to collections

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/Range.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WDouble.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WInteger.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WNumber.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WObject.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/RangeTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/StringTestCase.xtend

Adds randomUpTo(other) to integer and real numbers.
Deletes randomBetween(min, max) in Wollok object.
Adds new methods in Range, polymorphic to Collection.
Adds new javadoc comments in Integer and Range.
Fixes #730, #733 issues
This PR replaces old https://github.com/uqbar-project/wollok/pull/740, where base branch was erroneously master.

Dev range api

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/Interval.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/IntervalTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/WollokJavaConversions.xtend

See issue #738 
Also fixed a copy/paste problem in WollokJavaConversions for double.

Interval class for a set of continuous (real) numbers

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WDictionary.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/DictionaryTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/WollokJavaConversions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/natives/DefaultNativeObjectFactory.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/sdk/WollokDSK.xtend

Developed a new branch from dev (doesn't have test refactor for testing wollok classes, pull request pending for branch dev-test-easy).
Still doesn't support literals but has almost all methods from Map & Dictionary intersection (not union :))

Dictionary/Map support issue #387

---

org.uqbar.project.wollok.lib/src/wollok/lang/WInteger.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WNumber.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ObjectTest.xtend

Thanks @javierfernandes 
Close #771

Dev #771 error printing doubles in object property

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokNativeLobby.xtend

Changing error message 
Cannot use this in a program's code !
for 
Cannot use reference to self in a program's code !

Fix issue #710

---

org.uqbar.project.wollok.lib/src/wollok.wlk

Added javadoc for most of wollok objects (not for wollok game :smile: )

Dev javadoc wlk

---

org.uqbar.project.wollok.lib/src/wollok.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NullTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend

Related issue: #716 
See NullTestCases:
``` java
assert.throwsException({ null.sayHi() })
assert.throwsException({ null.toString() })
assert.throwsException({ null + 3 })
assert.throwsException({ null - 3 })
assert.throwsException({ null * 3 })
assert.throwsException({ null / 3 })
assert.throwsException({ null || true })
assert.throwsException({ null && true })
```
But I left == and !=:
``` java
assert.notThat(null == 8)
```

Dev null fix

---

org.uqbar.project.wollok/META-INF/MANIFEST.MF

Another "touch of the Death" ;)

Fixes #797 not resolving dependency to commons collections

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/StringTestCase.xtend

Minor issues of String methods
#708 
#709

Dev strings issues

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/AbstractWollokInterpreterTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/BooleanTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NullTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/VoidMethodsUsage.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/nonBooleanValueInBooleanOperationComponent.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/nonBooleanValueInIfCondition.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/nonBooleanValueInNotUnaryExpression.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/unnecessaryIf.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/unreachableCodeInBooleanBinaryOperation.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/unreachableCodeInIf.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokConstants.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Checkout the xpect tests to understand the different checks.

Dev #774 check non booleans in boolean exp

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/cannotReturnAssignment.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Please close the issue once you merge

Fixes #749 check cannot return an assignment

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CheckOnNameStyles.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Close #684 a simple typo error

Fix Issue #684

---

org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/startup/RemoveWizardsStartup.xtend
org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target
org.uqbar.project.wollok.updatesite/wollok-product.product

Well.....Subclipse has a bug. When you try to share a new project, the wizard page is empty. But if you resize it, show the content. Then @javierfernandes says "have you tried with subversive?". So i made the change and works fine. Besides all the menues are not filtered.

Dev #767 allow subclipse wizards

---

org.uqbar.project.wollok.sdk/feature.xml
org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target

It fixes issue #817. 
Allowing the update of 1.4.x to 1.5

Fixing dependencies of commons collections

---

org.uqbar.project.wollok.lib/src/wollok/game.wlk
org.uqbar.project.wollok.lib/src/wollok/lib.wlk
org.uqbar.project.wollok.lib/src/wollok/lib/GameObject.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/GameTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/PositionTest.xtend

Close #778 -> Breaking change!
Close #478

Dev #778 and #478 renaming game object and adding position create method

---

org.uqbar.project.wollok.lib/src/wollok/lang/WCollection.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WList.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WSet.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ListTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/SetTest.xtend

Fixing the errors and compares in the Lists 
@PalumboN

Fix equals for sets and lists #859 #865 #866

---

org.uqbar.project.wollok.lib/src/wollok/lib.wlk
org.uqbar.project.wollok.lib/src/wollok/lib/GameObject.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/GameTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/PositionTest.xtend

Adding:
```XTend
game.origin()
game.center()
aPosition.distance(otherPosition)
game.colliders(visual)
```
Close https://github.com/uqbar-project/wollok/issues/861

Add utils position methods

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend

Map returns list

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/dontDuplicateTestDescription.wtest.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Adding validation to duplicated test - Fixing #857

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend

Fixes #590.
@mmatos please see if it is working.
Thanks.

QuickFix create method in another file not working

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/mixins/MixinsTestCase.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokDsl.xtext
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/MixedMethodContainer.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokResourceDescriptionStrategy.xtend

Adding support for instantiation time mixing

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/numbers/NumberIdentityTest.xtend

Testing on my IDE I've got an error in 
XtextRunner
public XtextRunner(Class<?> klass) throws InitializationError {
super(klass);
}
No runnable methods.
See what Travis says.

Adding !== message. #934

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WDouble.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/DecimalTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend

Adding roundUp() & truncate() methods for Decimals

---

org.uqbar.project.wollok.lib/src/wollok/lang/WInteger.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/numbers/ArithmeticTest.xtend

Integer division #924

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/refactoring/ExtractMethodRefactoringTest.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/refactoring/ExtractMethodRefactoring.xtend

Fixes extract method refactor for using self instead of this.

Fix extract method

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WDate.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/DateTestCase.xtend

Added a ISO default toString method for wollok dates

Adding toString using ISO date format #964 | Test cases now in english

---

org.uqbar.project.wollok.lib/src/wollok/lang/WSet.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/SetTestCase.xtend

Fix anyOne() on sets

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend

Adding withoutDuplicates method for #983

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties
org.uqbar.project.wollok.updatesite/wollok-product.product

Forcing to use GTK Launcher for Linux Installation. Fixing #1040 issue.

New wollok wizard

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WCollection.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WSet.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/SetTestCase.xtend

Fix set comparison

---

appveyor.yml
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreter.xtend

Fixing Issue #896 
I have implemented the StackOverflowError of Wollok from the JAVA. 
The problem with the implementation with limits is that it depends in the platform it is running and the implementation of the interpreter.

Creating the stack overflow error from java's one

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/parserErrors/MisplacedInstanceVariable.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokDslRuntimeModule.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/parser/WollokSyntaxErrorMessageProvider.xtend

Customized error message for misplaced instance variables

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NullTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ComparingEqualityWKO.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Adding validation when comparing for equality

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/proposals/WollokContentAssistTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/WollokXPectTest.xtend

@tesonep Dario is joining Wollok team. He is working with me in Telecom and also he is a teacher in UNSAM. He has already installed Wollok Environment Setup and fixed both failing tests. This PR is just for Wollok Hackaton in UNQ. Please review it in order to  merge and have a "clean" dev version. Thanks!!

Fixing tests @Ignore for dev branch

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokDslUiModule.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/editor/syntaxcoloring/WollokAntlrTokenToAttributeIdMapper.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/highlight/WollokHighlightingConfiguration.xtend

Fix #1068 - The parsing of Wollok Docs

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend

No le agregué test porque no tengo ni idea de como hacer un test sobre una Consola de Eclipse. Lo probé manualmente sobre REPL creados a partir de archivos y sobre un REPL sin archivo.

add project and file description to REPL Console

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/WollokDslNewProjectWizard.java

fix #192 using a no default project location. Fix a minor bug related to #1075 separe wollok RPL name to source file info

fix #192 using a no default project location.

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WList.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ListTest.xtend

Primer prueba de modificar algo de wollok. Que alguien lo revise

Fix-#1039-sortBy-should-not-return-the-list

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk

now description matches the behaviour

fixed dayOfWeek() description

---

org.uqbar.project.wollok.ui/plugin.properties
org.uqbar.project.wollok.ui/plugin.xml
org.uqbar.project.wollok.ui/plugin_es.properties

I have modified plugin.xml and added a few constants to the property files (plugin.properties and plugin_es.properties).

#97 add a short description to wollok wizards

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/imports/ImportsTest.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokGlobalScopeProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/cache/MapBasedWollokGlobalScopeCache.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/cache/WollokGlobalScopeCache.xtend

Fixing the FQN in constructors

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NullTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/operation/WollokDeclarativeNativeBasicOperations.xtend

Fixing the identity checking with nulls

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/perspectives/WollokCodingPerspectiveFactory.xtend

A really small PR! 😄 
Hi @fdodino what do you think, putting the Static Diagram view next to the Outline View?

Putting the diagram window next to the outline

---

org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/actionbar/StaticDiagramToolbarActions.xtend

change javadoc and icon for CleanShapePositionsAction

---

.gitignore
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend

Quick fix hotfixes

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties

Remove unnused constant

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/ConsoleInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/TypeSystemXpectTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/objectEquality.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/WollokXPectTest.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/UnionType.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/AbstractInferenceStrategy.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/UserFriendlySupertype.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokClassFinder.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/libraries/AbstractWollokLib.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokResourceCache.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/sdk/WollokDSK.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/AbstractConfigurableDslValidator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Fixes 1187 and makes all tests run together again.

Fix 1187 ts compare by ==

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/editor/WollokTextEditor.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokDslScopeProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokGlobalScopeProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokImportScope.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokImportedNamespaceAwareLocalScopeProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/cache/MapBasedWollokGlobalScopeCache.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/cache/WollokGlobalScopeCache.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/root/WollokRootLocator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Fixes for #1204 #1220 #1230 #1232 #1255

Scopes and imports issues

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend

Fix #1272 - error while opening editor

---

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Messages.java
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokChecker.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherInterpreterEvaluator.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherParameters.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages.properties
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages_es.properties
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/DefaultWollokTestsReporter.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokConsoleTestsReporter.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokRemoteTestReporter.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokTestsReporter.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/json/WollokJSONTestsReporter.xtend
org.uqbar.project.wollok.ui.launch/plugin.xml
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokLinkListenerDelegate.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/WollokLaunchConstants.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/handlers/LaunchReplWithoutFileHandler.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/AbstractFileLaunchShortcut.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchDelegate.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchShortcut.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/WollokFileOpenerStrategy.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/WollokTestResultView.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/launch/WollokTestMainTab.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/model/WollokTestContainer.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/shortcut/WollokAllTestsLaunchShortcut.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/shortcut/WollokTestLaunchShortcut.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreter.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WEclipseUtils.xtend
org.uqbar.project.xinterpreter/src/org/uqbar/project/wollok/interpreter/api/XInterpreterEvaluator.xtend

Fixes
- #1189 
- #1209 
- #1218 
- #1219

Run all test fixes

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsolePage.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/actions/WollokReplConsoleActionsParticipant.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/editor/WollokReplConsolePartitioner.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/WollokLaunchUIMessages.java
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/messages.properties
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/messages_es.properties

Fixes 
- #1229 
- (when console view activated, button is not enabled if console is not running. Previously it did)
- i18n all console messages

Fix #1299 - REPL outdated source file

---

.travis.yml

Of course... it is only happening in dev branch!

Moving the logging of the used space to dev

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/if_advanced.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/void.wpgm.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/VoidTypeInfo.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/exceptions/CannotBeVoidException.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Type system fixes

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/ClosureInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/closures.wpgm.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/ClosureType.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend

Fixes #1167 
The problem was with return expressions inside closure declaration

Ts return in closures

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/ClosureInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/closures.wpgm.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/OpenMethod.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClassParameterTypeVariable.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClosureTypeInfo.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MessageSend.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokClassFinder.xtend

Support message sending to closures

---

org.uqbar.project.wollok.lib/src/wollok/lang/VoidObject.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ClosureTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NullTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/StringTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/VoidTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/VoidMethodsUsage.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/operation/WollokDeclarativeNativeBasicOperations.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

See #1298 
Also related to #1287

Fixing #1298 with tests

---

org.uqbar.project.wollok.lib/src/wollok/lib.wlk

This does not completely fix the issue, but is more like a short-term improvement.

partial-fix-1318-add-immutable-methods-to-position

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/numbers.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/properties.wlk.xt

@PalumboN @fdodino This are some fixes for problems introduced by #1406

Fixes detected in code review.

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/WollokTypeSystemTestInjector.xtend
org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typesystem/ui/builder/WollokTypeSystemBuilderParticipant.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystem.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/validator/WollokResourceUIValidatorExtension.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WEclipseUtils.xtend

@npasserini 
:smile:
It works fine (updates annotations in active editor only)

Enhanced multifile behavior for TS builder

---

org.uqbar.project.wollok.launch/Generate WollokDoc.launch
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Messages.java
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages.properties
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages_es.properties
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend
org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/startup/WollokPerspectiveListener.xtend
org.uqbar.project.wollok.ui.launch/plugin.xml
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsolePage.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchDelegate.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchShortcut.xtend
org.uqbar.project.wollok.ui/plugin.xml
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/perspectives/WollokCodingPerspectiveFactory.xtend

Issues
- #1209 : repeated run configuration
- #1433: removing all consoles before running REPL + console running status (gray background)
- #1470: run icon

Console enhancements

---

org.uqbar.project.wollok.launch/Generate WollokDoc.launch
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/wollokDoc/WollokDocParser.xtend
org.uqbar.project.wollok.lib/src/wollok/game.wlk
org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lib.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/debugger/DebugWithoutThreadingTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/natives/ExceptionPropagationInNativeTestCase.xtend

Bueno, está deployado en http://www.wollok.org , más concretamente en
http://www.wollok.org/documentacion/wollokdoc/
Agregué más ejemplos para Date, Number, Dictionary, game, keyboard, List, Set, además de aclarar las operaciones que requieren que la colección no esté vacía para los últimos dos casos.
Fix de #1267 y #1463
También marqué como @Ignored dos tests que estuve manteniendo por dos años pero es terriblemente tedioso seguir haciéndolo (esperaremos entonces a reflotar en algún momento el Debugger)

Wollok doc enhancements

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/validations/mixins/MixedMethodContainerInstantiation.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Basically what's written in the title. Added 2 tests also.

Fix #1489 instantiation with mixed method containers

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/mixins/MixinsTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/MixedMethodContainer.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/ToStringBuilder.xtend

Fixes toString() error for mixed method containers

fix #1488 toString() for mixed method containers

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DuplicatedInstanceVariable.wtest.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokDslScopeProvider.xtend

Fix #1520 local variables describe

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/formatter/TestingFormatterTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting2/WollokDslFormatter.xtend

Fixing #1531 - formatter issue for methods in describe

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/actions/WollokReplConsoleActionsParticipant.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/WollokLaunchUIMessages.java
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/messages.properties
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/messages_es.properties

Fix #340 - add a clear history button for console

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/MethodTypeInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/super.wlk.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstructorConstraintsGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/CrossReferenceConstraintsGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/DelegatingConstructorCallConstraintsGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/OverridingConstraintsGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/SuperConstraintsGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/SuperInvocationConstraintsGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend

Fix https://github.com/uqbar-project/wollok/issues/1567
Adding _SuperInvocation_ and _Super/Self DelegatingConstructorCall_.

Ts super invocation

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/describe.wtest.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/fixture.wtest.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/tests.wtest.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/SuiteType.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend

Fix https://github.com/uqbar-project/wollok/issues/1591

Add tests to ts

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/failureMessages.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/objectLiterals.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/super.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/void.wpgm.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/ObjectLiteralType.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystemException.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/PropagateMaximalTypes.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/PropagateMinimalTypes.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/AnalysisResultReporter.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ConcreteTypeState.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableOwner.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/exceptions/RejectedMinTypeException.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend

Fix https://github.com/uqbar-project/wollok/issues/1587

Method body inference before message send in parameters

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/CollectionInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/collections.wlk.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/CollectionTypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/SubtypingRules.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/CompoundSelfTypeVariableSchema.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/CompoundTypeVariableSchema.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableSchema.xtend

Fix https://github.com/uqbar-project/wollok/issues/1580
Fix https://github.com/uqbar-project/wollok/issues/1621
:)

Fix SelfType 

---

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Messages.java
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokChecker.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherParameters.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages.properties
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages_es.properties
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/wollokDoc/WollokDocParser.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableOwner.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchDelegate.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchShortcut.xtend

Add configuration to the launcher to decide when to run validations

---

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/IfTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreter.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend

Ver #1620, además arregla un temita que tuve ayer con el merge a dev para solucionar #1636 (está mostrando el stack trace de todos los errores, incluso los del intérprete)

Fix #1620 - If condition with something different than a boolean

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/game.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/position.wlk.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokGameTypeDeclarations.xtend

Fix https://github.com/uqbar-project/wollok/issues/1586
Me la jugué y fui por esto... y no me arrepiento de nada! Lo probé con un TP de PepitaGame de este cuatri y salió todo hermoso.

[WG] Tipar los objetos en una celda

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/contentassist/BasicTypeResolver.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend

Idea alternativa para isGlobal

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/actions/WollokReplConsoleActionsParticipant.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/extensions/WollokConsoleExtensions.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchDelegate.xtend

Forcing shutdown of console when starting a new one

Fix #1618 Repl optimization

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/labeling/WollokDslLabelProvider.xtend

Authors: Mauro Casciati, Alejandro Dini, Nicolás Viotti

fix: #1605 - outline message arguments

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WNumber.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WString.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/StringTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/strings.wlk.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/StringTypeDeclarations.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/WollokJavaConversions.xtend

Fix #1543
Hecho en conjunto con @isaiaslafon y @gustavososa92 :smiley:

New string methods

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/parser/MethodParserTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/parser/TestParserTest.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/parser/WollokSyntaxErrorMessageProvider.xtend

Fix #1286 code outside a fixture

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokGlobalScopeProvider.xtend

This fixes 99,9% of deadlocks in Wollok - I hope

Small change, big deal

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/quickfix/SelfQuickFixTest.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/Messages.java
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Add quickfix when calling wko inside the same wko

---

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchDelegate.xtend

Also import wgame automatically to REPL sessions.

Allow imports in REPL.

---

org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/model/Connection.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokGlobalScopeProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/StringUtils.xtend

Fixes #1712 
Also a small change to avoid another deadlock (??) while building the environment

Fix #1712 - creating a connection with null name produced a NPE

---

org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokCodeHighLightLineStyleListener.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokGlobalScopeProvider.xtend

Imports repl highlight fix #1707

---

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/debugger/server/rmi/XDebugStackFrame.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/debugger/server/rmi/XDebugStackFrameVariable.xtend
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend
org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/model/Shape.xtend
org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/parts/AbstractMethodContainerEditPart.xtend
org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/view/AbstractClassMemberFigure.xtend
org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/dynamic/DynamicDiagramView.xtend
org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/dynamic/parts/VariableModel.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokNativeLobby.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/sdk/WollokSDK.xtend
org.uqbar.project.xinterpreter/src/org/uqbar/project/wollok/interpreter/context/CompositeEvaluationContext.xtend
org.uqbar.project.xinterpreter/src/org/uqbar/project/wollok/interpreter/context/EvaluationContext.xtend
org.uqbar.project.xinterpreter/src/org/uqbar/project/wollok/interpreter/context/MapBasedEvaluationContext.xtend

- Several references are joined, separated by ", "
- You don't see global wko references unless you create a local reference in the console

Dynamic diagram #1710 core objects

---

org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/AbstractJavaWrapper.xtend
org.uqbar.project.wollok.lib/src/wollok/lang/WDate.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/DateTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokGlobalScopeProvider.xtend

Fix #1711 - new Date() attributes initialization

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/contentassist/WollokDslProposalProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend

Me gustó que además ordené la clase WollokDslProposalProvider que era un spaghetti entremezclado de métodos helpers y los que verdaderamente necesita el autocomplete. Más tranquilo voy a ver si preparo lo de los tests para que parsee una expresión como AST y verifique qué autocomplete le cabe a una expresión.
Fixea #1325

Autocomplete properties #1325

---

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/debugger/server/rmi/XWollokObjectDebugValue.xtend
org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.lib/src/wollok/lang/WString.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/TestTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ObjectTest.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WollokObjectUtils.xtend

Fix #1563 - REPL doesn't show "" for Strings in collection

---

org.uqbar.project.wollok.lib/src/wollok/lang/WDate.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/DateTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend

Fix #1752 - Bad wollok date after operation returning a date

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/WollokProjectCreator.xtend

Fix #676 - weird warnings on new empty project

---

org.uqbar.project.wollok.lib/src/wollok/game.wlk
org.uqbar.project.wollok.lib/src/wollok/lang.wlk
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/GameTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/ConsoleInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/CoreInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/MethodTypeInferenceTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/NamedObjectInferenceTestCase.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/CollectionTypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/DateTypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/NumberTypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokGameTypeDeclarations.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/sdk/WollokSDK.xtend

- Agrego las notaciones de tipos para algunos métodos del CORE que faltaban (y agregué un test para esto no vuelva a suceder).
- También agregué un método en `game` que queremos con Nico (Y eso me llevó a tocar Collection).

Ts declarations test

---

README.md

Actualización  del link de documentación del lenguaje

Actualizo Link de documentación del lenguaje

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DuplicatedReferenceFromImports.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DuplicatedReferenceFromImports.wtest.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Fix #1776 - Ajuste fino de los mensajes de error ante superposición de nombres de referencia

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/Messages.java
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/QuickFixUtils.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/libraries/WollokLibExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokImportedNamespaceAwareLocalScopeProvider.xtend

Enhancement #1726 - quick fix - agregar import de un elemento no existente

---

org.uqbar.project.wollok.tests/formatters.launch
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/formatter/AbstractWollokFormatterTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/formatter/TestingFormatterTestCase.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting2/WollokDslFormatter.xtend

Not a big deal, just fixing internal conflicts. Also added a launcher for running only formatter tests.

Fix #1830 - formatter conflicts

---

org.uqbar.project.wollok.tests/formatters.launch
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/formatter/AbstractWollokFormatterTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/formatter/TestingFormatterTestCase.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DuplicatedReferenceFromImportsInDescribeName.wtest.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting2/WollokDslFormatter.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

-  Se fixea los problemas entre los imports modificando los params del validator
Fix #1846

Fix #1846 collision between imports and describes

---

.travis.yml
README.md
org.uqbar.project.wollok.game/META-INF/MANIFEST.MF
org.uqbar.project.wollok.launch/META-INF/MANIFEST.MF
org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Wollok.xtend
org.uqbar.project.wollok.lib/META-INF/MANIFEST.MF
org.uqbar.project.wollok.product.ui/META-INF/MANIFEST.MF
org.uqbar.project.wollok.product/META-INF/MANIFEST.MF
org.uqbar.project.wollok.product/plugin.xml
org.uqbar.project.wollok.sdk/feature.xml
org.uqbar.project.wollok.tests/META-INF/MANIFEST.MF
org.uqbar.project.wollok.typeSystem.ui/META-INF/MANIFEST.MF
org.uqbar.project.wollok.typeSystem/META-INF/MANIFEST.MF
org.uqbar.project.wollok.ui.diagrams/META-INF/MANIFEST.MF
org.uqbar.project.wollok.ui.launch/META-INF/MANIFEST.MF
org.uqbar.project.wollok.ui/META-INF/MANIFEST.MF
org.uqbar.project.wollok.updatesite/category.xml
org.uqbar.project.wollok.updatesite/wollok-product.product
org.uqbar.project.wollok/META-INF/MANIFEST.MF
org.uqbar.project.xinterpreter/META-INF/MANIFEST.MF

Preparing 1.9.2 release (last 32 bits)

1.9.2 release

---

org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/inheritParameters.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/properties.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/NamedParameters.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/PropertiesDefinition.wtest.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/PropertiesInitializationInConstructorCall.wtest.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Es el famoso fix a #1808  @PalumboN ... fijate si tiene sentido.

Fix #1808 constructor call property const

---

org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target

Also pointing to new wollok-language `master` branch

Sgit upgrade

---

org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Fix #1872 - adding quick fix for global variables

---

org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/interpreter/listeners/WollokRemoteContextStateListener.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/closures-advanced.wlk.xt
org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/editparts/ConnectionEditPart.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/debugger/model/WollokVariable.xtend
org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/tests/WollokTestResultView.xtend
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/Messages.java
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/ResourceUtils.xtend

- Mejora de íconos de la solapa Wollok Test
- Resolvemos #1904 
- De yapa, metí un fix para #1903, que consistió en a) evitar que tire un Dialog por NPE, b) resolver la causa original del problema que es no mostrar la flecha raíz de un objeto autodefinido para los archivos de tests.
- ah, y localmente tuve que meter un cambio en un test del type system que me estaba fallando

Fix #1904 dynamic diagram inside describe

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties

Fix #1924 Missing i18 message for only flag validation

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/closures-advanced.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/testFailures.wlk.xt
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/GuessMinTypeFromMaxType.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/RecursiveTypeValidator.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend

Fix https://github.com/uqbar-project/wollok/issues/1804

Infinite list type

---

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/ArrowListener.xtend
org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/KeyboardListener.xtend
org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/WollokKeycodeToLibGDX.xtend
org.uqbar.project.wollok.lib/src/wollok/game/GameObject.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/KeyboardListenerTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/GameTest.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokGameTypeDeclarations.xtend

Fix https://github.com/uqbar-project/wollok/issues/1929
Update de este cambio: https://github.com/uqbar-project/wollok-language/pull/68

Keycode update

---

org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties

Una pavada, arreglamos un typo en el mensaje

Fix #1947 - validator message

---

org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/validations/mixins/MixinAndClassAttributes.wlk.xt
org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend

Fix #1917 constructor call validation for class/mixin linearization

---

org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/VisualComponent.xtend
org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend
org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/helpers/WollokConventionExtensions.xtend
org.uqbar.project.wollok.lib/src/wollok/game/GameObject.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/GameTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ImageTest.xtend
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DuplicatedInstanceVariableInHierarchy.wlk.xt
org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/validations/mixins/MixinAndClassAttributes.wlk.xt
org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties

Este PR arregla un bug que había quedado en https://github.com/uqbar-project/wollok/pull/1986
De paso arreglé 2 issues menores, que estaba dejando para la gente nueva, pero la gente nueva no va a venir acá.

Fix game position
